# Generated by Django 5.2.4 on 2025-11-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expensename',
            new_name='name',
        ),
    ]
